name: Deploy QuestionBank

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd /var/www/QuestionBank

            echo "Current commit:"
            git rev-parse --short HEAD

            echo "Pulling latest code..."
            git pull origin main

            echo "New commit:"
            git rev-parse --short HEAD

            echo "Code update successful!"
